//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate
    {
        public int CertificateId { get; set; }
        public string CertificateName { get; set; }
        public string CertificateAuthority { get; set; }
        public string LevelCertificate { get; set; }
        public Nullable<System.DateTime> FromYear { get; set; }
        public Nullable<int> EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
