//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.PostJobs = new HashSet<PostJob>();
        }
    
        public int JobId { get; set; }
        public string JobTitle { get; set; }
        public string JobRequirement { get; set; }
        public string JobDetail { get; set; }
        public Nullable<int> JobCategoryId { get; set; }
    
        public virtual JobCategory JobCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PostJob> PostJobs { get; set; }
    }
}
