//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRequirementsDetail
    {
        public int JobRequirementDetailID { get; set; }
        public string JobRquirementsDetails { get; set; }
        public Nullable<int> JobRequirementID { get; set; }
    
        public virtual JobRequirement JobRequirement { get; set; }
    }
}
