//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostJob
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PostJob()
        {
            this.JobApplies = new HashSet<JobApply>();
        }
    
        public int PostJobId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<int> RquiredPerson { get; set; }
        public string Qualification { get; set; }
        public Nullable<int> ManimumExperience { get; set; }
        public Nullable<int> AgeLimit { get; set; }
        public string MarriedStatus { get; set; }
        public string StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> ShortlistDate { get; set; }
        public Nullable<System.DateTime> InterviewDate { get; set; }
        public Nullable<int> JobStatusId { get; set; }
        public string Desctription { get; set; }
        public Nullable<int> JobCategoryId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Company Company1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobApply> JobApplies { get; set; }
        public virtual JobCategory JobCategory { get; set; }
        public virtual Job Job { get; set; }
        public virtual JobStatu JobStatu { get; set; }
        public virtual User User { get; set; }
    }
}
